### ISSUE TITLE
Cable with numbered cores

### ISSUE THREAD

**Issue by zfarkas88** [wireviz/WireViz#319]
Hi,

would it be possible to visualize somehow cables with numbered cores?

Thank you in advance!

![](https://products.lappgroup.com/typo3temp/_processed_/d/4/csm_OELFLEX_1119752_PRODUCT_3_66f971faa218ea666be2c7cea5c000829df1039d_4a08dcbb0a.jpg)

Colour code: VDE 0293-334

**Comment by kvid** [comment]
As long as all wires (cores?) in the cable are numbered 1, 2, 3, 4, etc. - then this is already supported, but custom numbering that differs from the sequence of natural numbers (similar to custom pin numbering of a connector) is not currently supported.

**Comment by zfarkas88** [comment]
by visualisation I mean something like this
![github](https://github.com/wireviz/WireViz/assets/11296095/3bf1e5c0-498a-42ff-82d8-8276e5742482)


```
connectors:
  X1:
    type: Molex MX150L
    subtype: female
    pinlabels: [Pin 1, Pin 2, Pin 3, Pin 4, Pin 5, Pin 6]
    notes: Connector 1
  X2:
    type: Molex MX150L
    subtype: female
    pinlabels: [Pin 1, Pin 2, Pin 3, Pin 4, Pin 5, Pin 6]
    notes: Connector 2  

cables:
  K43:
    gauge: 0.75 mm2
    length: 8
    colors: [BK,BK,BK,BK,BK,YEGN]
    wirecount: 6
    shield: false
    wirelabels: ["1","2","3","4","5","6"]
  
connections:
    - #K43
        - X1: [1,2,3,4,5,6]
        - K43: [1,2,3,4,5,6]
        - X2: [1,2,3,4,5,6]
```
