### ISSUE TITLE
Shield/Screen individual cores

### ISSUE THREAD

**Issue by scottbouch** [wireviz/WireViz#330]
Hi, I need to draw a cable where only two cores of a 4 core cable are screened. Presently I have just added a note to the cable properties, but it would be nice to be able to show it with oval shaped rings around the screened cores as you would see in diagrams.

Is there a way to graphically show screens on individual cores?

My example: https://scottbouch.com/tmp/UHF2.html

(Many thanks for this wonderful solution to drawing cables, I love it!)

Cheers, Scott

**Comment by kvid** [comment]
@scottbouch, thank you for sharing your use case. I don't know how to better accomplish your request with the current versions, but maybe a future version can support this. See also #56 for other discussions about complicated cable structures. Before starting a PR adding such a feature, it might be a good idea to discuss here:
1. How flexible should such a new feature be?
      - Should we support more than one group of shielded wires?
      - Should we support outer levels shielding containing other shield groups and wires?
      - Should we support other shield properties, like e.g. foil, braid, etc.?
      - Should we also support other features that are shared in subsets of wires, like e.g. twisted pairs (until #3 is resolved), wrapped binder groups, etc.?
2. How can we easily specify it in the YAML input syntax without making it too complicated for the simple cases?
3. How can we visualize it clearly in the diagram?
4. Do we need to add any cable shield details in the BOM description?
5. How much of these features might also be supported for connectors? (See #285)

As suggestions to points 2 and 3 above, see 2 examples below that still allow the original syntax for the simple cases:
```yaml
cables:
  w:
    colors: [RD, BU, YE, GN]
    shield: [YE, GN]
```
![issue330x gv](https://github.com/wireviz/WireViz/assets/12657033/f95b5912-40b2-4c41-9b14-b76f1d7cce30)
```yaml
cables:
  w:
    colors: [RD, BU, YE, GN]
    shield:
      ShieldP1: [RD, BU]
      ShieldP2: [YE, GN]
      ShieldAll: [ShieldP1, ShieldP2]
```
![issue330y gv](https://github.com/wireviz/WireViz/assets/12657033/e0ccfdfd-6b96-4e7d-a558-11d44aa31c3d)
