### ISSUE TITLE
[request] BOM quantities and units

### ISSUE THREAD

**Issue by scottbouch** [wireviz/WireViz#343]
Hi, one further request...

I came across a little frustration: quantities in the BOM for connector parts is limited to integers, ie, for counting items. but cables can have measurements.

There are some circumstances where a measurement is needed for connector parts, such as length or volume where a quantity of a material resource is cut for use.

For example:

**_Lengths:_**
- A cut length of heat-shrink sleeving to be applied over the end of a cable where a connector cable clamp or gland is applied, there is a need to specify the length. This may be to tidy up trimmed screen/shield, or to make up the thickness of the outer jacket for more effective strain-relief clamping, and sometimes to provide a cable bend-radius strain relief.
- Cut lengths of sleeves to cover the soldered joints to connector contacts.
- Where a short wire is soldered to the cut off screen/shield of a cable for termination, it would be useful to add the length of this short wire to the connector BoM. 
- I also have some connectors requiring turns of lashing cord/thread to provide strain-relief around the wires, it would be good to specify the length of lashing cord/thread to cut for use.

**_Volumes:_**
- Some connectors and glands are "potted" in resin or an RTV compound, so a volume quantity would be helpful too.
- Glues and thread-lock also are sometimes used, but maybe the quantity here could be "AR" for As Required.
- Liquid volumes could be measured by weight, too, such as the resin and activator to use.

**_Units_**
- It would be great if the unit can be custom specified by the user for the given quantity.

Hope all of this makes sense! :)

Maybe its easiest to just allow the quantity to be a float instead of an integer. Or maybe add a little logic to and change the quantity variable to a float if a unit is specified. Without a unit we can probably assume its just a count, and an integer will be fine.

_**Additional total column**_
This could allow for easier calculation of total quantities required of a certain material... such as eg: 25 heat-shrink sleeves to be applied to the soldered joints of a connector, each sleeve is 12mm long, so the BOM could present a total column showing 300 mm of this item is required.

Cheers, Scott;

**Comment by kvid** [comment]
Hi Scott,

What version of WireViz are you using?

Quantities in the BOM are NOT limited to integers. Several [examples](https://github.com/wireviz/WireViz/blob/master/examples/readme.md) use decimal numbers as lengths.

> Maybe its easiest to add a text variable for unit, and allow the quantity to be a float instead of an integer.

This is exactly how it is implemented (and documented in [syntax.md](https://github.com/wireviz/WireViz/blob/master/docs/syntax.md)).

The `cable.length` has a simplified syntax accepting unit as a string after the number, separated by a space (even though it's currently implemented with an internal non-documented `length_unit` attribute behind the scene). For other quantities, an extra `unit` attribute must be used, but maybe these also will be simplified in future versions.

Default unit for `cable.length` is `m` when not specified. For other quantities, an empty unit is default (i.e. a count).

You can use any text string as unit, but note that only entries with exact same units are added up in the BOM. No unit conversion is currently implemented.

Try including something like this in your harness:
```yaml
cables:
  Long cable:
    colors: [BK, WH]
    length: 0.1 km
  Test cable:
    colors: [RD, BK]
    length: 2.5 yard
    additional_components:
      - type: Heat-shrink
        qty: 1.5
        unit: inch
      - type: Resin
        qty: 0.2
        unit: dl
additional_bom_items:
  - description: Item not in diagram
    qty: 11.5
    unit: mm
connections:
  - - Test cable
  - - Long cable
```
