### ISSUE TITLE
[Bug?] Exception: <== is not in cables

### ISSUE THREAD

**Issue by RubenHeyse** [wireviz/WireViz#356]
I'm currently designing a simple wiring harness and encountering an error stating `Exception: <== is not in cables` when trying to link a simple crimped pin to it's connector. I've been following the arrow syntax in [the syntax guide](https://github.com/wireviz/WireViz/blob/master/docs/syntax.md).
The Yaml File is:
```yml
connectors:
  X1:
    type: Plug
    pins: [A, B, C, D, E, F, G, H, J, K, L, M, N, P]
    pinlabels: [GND, 12V, J1939+, J1939-]
    pincolors: [BK, RD, YE, GN]
    pincount: 14
    show_pincount: true
    hide_disconnected_pins: true
    notes: |
      Unconnected pins are not shown
      Cavity plugs are to be fitted in unpopulated holes
    image: 
      src: Images/HDP26-18-14SE-CL20.jpg
      height: 150
      caption: "DEUTSCH: HDP26-18-14SE-CL20"
    manufacturer: DEUTSCH
    mpn: HDP26-18-14SE-CL20
    additional_components:
    -
      type: "Cavity Plug"
      qty: 10
      manufacturer: DEUTSCH    
      mpn: 2373921-1

  X2:
    type: Receptacle
    pinlabels: [12V, GND, CAN HI, CAN LO]
    pincolors: [RD, BK, YE, GN]
    image:
      src: Images/DT04-4P-CE03.jpeg
      height: 150
      caption: "DEUTSCH: DT04-4P-CE03"
    manufacturer: DEUTSCH
    mpn: DT04-4P-CE03

  PIN:
    style: simple
    autogenerate: true
    type: Crimped Pin
    manufacturer: DEUTSCH
    mpn: 1060-16-0622

  SOCKET:
    style: simple
    autogenerate: true
    type: Crimped Socket
    manufacturer: DEUTSCH
    mpn: 1062-16-0177


cables:
  W1:
    category: bundle
    gauge: 1 mm2
    length: 500 mm
    colors: [BK, RD, YE, GN]
    show_equiv: true
    mpn: [TW100-B-500, TW100-R-500, TW100-Y-500, TW100-DG-500]
    notes: |
      Red and Black are a twisted pair with 25mm pitch
      Yellow and Green are a twisted pair with 25mm pitch
    additional_components:
    -
      type: Conduit
      subtype: Black Plastic, 12mm
      qty: 470 
      unit: mm
      mpn: CTPA12
    -
      type: Heat Shrink
      subtype: Adhesive Lined
      qty: 2

connections:
  -
    - X1: [A, B, C, D]
    - <==
    - SOCKET.
    - W1: [1, 2, 3, 4]
    - PIN.
    - ==>
    - X2: [2, 1, 3, 4]
```
Is this down to an installation issue?
