### ISSUE TITLE
[feature] Single wire cable with `style: simple`

### ISSUE THREAD

**Issue by martinrieder** [wireviz/WireViz#376]
The following example brings up an interesting use case for cables containing only a single wire. Similar to the way that connectors can be defined with `style: simple`, I suggest to implement cables with this attribute. It would not be displayed as a box and should optionally show the wire name/label. 

_ Credits to @EloiVilalta in https://github.com/wireviz/WireViz/issues/293#issuecomment-2150401138_

```yaml
connectors:
  C1:
    style: simple
    type: Connector
  C2:
    style: simple
    type: Connector      
cables:  
  W1:
    wirecount: 1
    show_name: false
    show_wirecount: false
    colors: [RD]

connections:
  -
    - C1: [1]
    - W1: [1]
    - C2: [1]
``` 

The issue with the current implementation is that it requires a lot of space in the graph due to the HTML table. This is not needed for only displaying a the wire label/name as a text. 

![image](https://github.com/wireviz/WireViz/assets/32335173/74517787-c508-43d7-8bac-a23e602dea0b)
