### ISSUE TITLE
[query] Dot notation error in Wireviz

### ISSUE THREAD

**Issue by akikinho** [wireviz/WireViz#393]
Hello Wireviz Team,
I am trying to understand the usage of dot notation in Wireviz but unable to replicate as it throws an exception 'First item not found anywhere.' The operating system is Microsoft Windows 10 Pro Version 10.0.19045 Build 19045 and the Wireviz version is wireviz 0.3.2. Can you please help?

```
connectors:
  X:
    pinlabels: [GND,B-,A+]
    color: GN
    
cables:
  W:
    colors: [BN,YE,GN]
    shield: true
    
connections:
  -
    - X.: [1-3]
    - W.W1: [1-3]
    - X.: [1-3]   
```

**Comment by kvid** [comment]
The dot notation is new from v0.4 - see docs/CHANGELOG.

**Comment by akikinho** [comment]
Thank you @kvid.

**Comment by akikinho** [comment]
@kvid I am getting this error. How do I rectify this?
OSError: [WinError 123]

**Comment by akikinho** [comment]
Hello,
Here are the different versions installed, but facing issues.
Package         Version
--------------- -----------
click           8.1.7
colorama        0.4.6
graphviz        0.20.3
numpy           1.26.4
pandas          2.2.2
pillow          10.3.0
pip             24.0
python-dateutil 2.9.0.post0
pytz            2024.1
PyYAML          6.0.1
setuptools      70.1.0
six             1.16.0
tzdata          2024.1
wireviz         0.4

Microsoft Windows [Version 10.0.19045.4529]

Error:  File "<frozen ntpath>", line 722, in realpath
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect. Can you please help?

**Comment by kvid** [comment]
Please provide your Python version (`python -V`). However, your latest error message is similar to what was reported in #344, so I guess the issue is already fixed in PR #346 that is merged into PR #365 (work-in-progress) that will become our next release when finished.

Try this development version to see if it solves your latest problem:
```sh
pip uninstall wireviz
pip install git+https://github.com/wireviz/WireViz@release/v0.4.1-rc
```

**Comment by akikinho** [comment]
Thank you @kvid. The python version is Python 3.12.3.

**Comment by kvid** [comment]
@akikinho - I just deleted your comment in #293 because it seemed to be a copy of your original comment in this issue, and it was not at all related to what is discussed in #293.

**Comment by akikinho** [comment]
@kvid, it is correct and thank you. I have a new question.
In the dot notation, I found that the connector name is missing.

```
connectors:
  X:
    pinlabels: [GND,B-,A+]
    color: GN
    
  Y:
    pinlabels: [SH,B+,A-]
    color: RD
    
cables:
  W:
    colors: [BN,YE,GN]
    shield: true
    
connections:
-
    - X: [2]
    - W: [3]
    - Y: [3]
-
    - X.: [1,2,3]
    - W.W1: [1,2,3]
    - X.: [1,2,3]   
```
