### ISSUE TITLE
How to deal with a lot of connection ?

### ISSUE THREAD

**Issue by bigboss59400** [wireviz/WireViz#413]
hello,
I have a big connector (100+ pins), I can't find a way to make it more viewable, I thought about increasing the space between the connector and the connections however I don't know if it's psosible ? if so how to do it ? is it possible to apply this kind of settings only for a particular connector ?

I'm open to suggestions too

![Capture d’écran 2024-07-20 171048](https://github.com/user-attachments/assets/07f8eee0-93da-4733-9c43-93729869ff92)

**Comment by kvid** [comment]
This looks very similar to #174, so I recommend a similar work-around:
```yaml
tweak:
  override:
    graph:
      ranksep: '6'  # Larger horizontal separation between all nodes
```
Default `ranksep` value is 2. You should try out how much you need to increase it in your use case.

Unless you argue why your use case is not covered by #174, I'm tempted to close this issue as a duplicate.
