### ISSUE TITLE
Twin Ferrule implementation

### ISSUE THREAD

**Issue by DaControl** [wireviz/WireViz#419]
Hi,

I am wondering if something like a twin ferrule is existing. Or if it is possible, to get the wire the same direction as the other one goes in.

I am new in WireViz and I would love to use it, but I know, I would use a lot of twin ferrules.

![7100199](https://github.com/user-attachments/assets/89ce3059-b3dc-4e66-8020-f30df48be6c2)

```
connectors:
  X1:
    type: Hirose DF3
    pincount: 6
    pn: DF3-6S-2C

  F1:
    style: simple
    type: Crimp ferrule
    subtype: 0.25 mm²
    color: TQ
    pn: 460006

  F2:
    style: simple
    type: Crimp ferrule
    subtype: 0.5 mm²
    color: WH
    pn: 470108

cables:
  W1:
    category: bundle
    gauge: 0.25 mm²
    wirecount: 3
    colors: [OG, GN, WH]
    wirelabels: [50cm, 42cm, 42cm]
    pn: [55A0111-24-3, 55A0111-24-5, 55A0111-24-9]
    additional_components:
      - type: Braided sleeving
        subtype: Braided sleeving PET 2-6 mm
        qty: 35
        unit: cm
        pn: 170-81100

  W2:
    gauge: 0.25 mm²
    wirecount: 1
    colors: [OG]
    wirelabels: [8cm]
    pn: 55A0111-24-3

connections:
  -
    - X1: [2-3]
    - W1: [2-3]
    - F1.

  -
    - X1: [1]
    - W1: [1]
    - F2.
    - W2: [1]
    - F1.
```

**Comment by kvid** [comment]
@DaControl - Thank you for presenting your use case.

1. You ask for a "twin ferrule", and I understand that term as a ferrule where two stripped wire ends are electrically connected by inserting both into the same ferrule and then crimped together. If my understanding is equal yours, then you have already achieved this with your `F2.` entry in your harness above where `W1:1` and `W2:1` are electrically connected together.

2. Then you ask for a way to control the direction of the wires entering the connector (ferrule in your case). That has already been discussed and explained in earlier issues, e.g. #293. Electrically, it doesn't matter which direction the wires are drawn in/out of the connectors, but controlling it might improve the diagram readability sometimes. In your case you can reverse the `W2` drawing direction by replacing your connections with these:
```yaml
connections:
  -
    - X1: [2-3]
    - W1: [2-3]
    - F1.
  -
    - X1: [1]
    - W1: [1]
    - F2.F3
  -
    - F1.
    - W2: [1]
    - F3
```
Your last connection set is split in two to reverse the last part, and I selected a new identifier `F3` to enable connecting the same ferrule from two different connection sets. See the result below:
![issue419a](https://github.com/user-attachments/assets/dd750c2a-e95c-4e8c-9a76-8e0308a97f13)
Is this what you had in mind?
