### ISSUE TITLE
template placeholders example needed

### ISSUE THREAD

**Issue by ask6483** [wireviz/WireViz#424]
I don't quite understand how to use custom placeholders in template, is there any examples how to use this?

![image](https://github.com/user-attachments/assets/67f0c17d-11d6-4edd-ab9f-7f787ebe2584)

What I try to achieve is accessing drawing.number and drawing.file:
```
metadata:
  title: 'bla bla'
  description: 'bla bla'
  pn: '1005004'
  date: '08.07.2024'
  template:
    name: '../templates/simple'
  drawing:
    number: 'ASE 100 E 254 - C'
    file: '../drawings/file.pdf'
```

Tried `<!-- %drawing_number% -->`, `<!-- %drawing_0_number% -->`, `<!-- %drawing.number% -->`?

**Comment by kvid** [comment]
@ask6483 - Thank you for describing your use case. Unfortunately, what you ask for is not (yet?) supported.

Custom metadata supported in v0.4.1:
- Simple {item} str/int/float value as `<!-- %{item}% -->`
- Dict {item} of dicts {category} of {key} str/int/float values as `<!-- %{item}_{i}% -->` and `<!-- %{item}_{i}_{key}% -->` where `{i}` is 1 for the first {category}, 2 for the second, etc.

The metadata below demonstrates the latter, and can e.g. be referenced as `<p><!-- %drawings_1% --> drawing: <a href="<!-- %drawings_1_file% -->"><!-- %drawings_1_number% --></a></p>` in the template.
```
metadata:
  drawings:
    Initial:
      number: 'ASE 100 E 254 - C'
      file: '../drawings/file.pdf'
```

The TODO at https://github.com/wireviz/WireViz/blob/v0.4.1/src/wireviz/wv_html.py#L118 might be a solution to what you expect to support `<!-- %drawing_number% -->`, but it's not thoroughly tested.
