### ISSUE TITLE
[query] Is it possible to order the pins in descending order?

### ISSUE THREAD

**Issue by AdriZ** [wireviz/WireViz#427]
I have a cable that is straightforward but the pin numbering is in opposite way on each connector.

Is it possible to order pins in descending order or another solution to arrange that?
![image](https://github.com/user-attachments/assets/b6a0e76e-bf7b-45e1-86f2-3b5a7c0e5b5e)

Here is my yml file renamed with .txt to be accepted by Github.
[example.yml.txt](https://github.com/user-attachments/files/17495780/example.yml.txt)

**Comment by kvid** [comment]
It's possible to specify custom pin names in any order you want:
```yaml
  pins: [12,11,10,9,8,7,6,5,4,3,2,1]
  pinlabels: [...]  # NB: The pin labels are expected to be in the same order.
```
See also #279 for a suggested future alternative that could be useful in your use case.

**Comment by DeflateAwning** [comment]
What does the comment "The pin labels are expected to be in the same order." mean? Assuming P1 is Pin #1, Pin 12 is Pin #2, etc., which of these is correct?

```yaml
# Option 1 (Update: Correct)
pins: [12,11,10,9,8,7,6,5,4,3,2,1]
pinlabels: [P12, P11, P10, P9, P8, P7, P6, P5, P4, P3, P2, P1]  # NB: The pin labels are expected to be in the same order. (??)

# Option 2 (Update: Don't use this one)
pins: [12,11,10,9,8,7,6,5,4,3,2,1]
pinlabels: [P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12]  # NB: The pin labels are expected to be in the same order. (??)
```
