### ISSUE TITLE
Add a way to add a loopback wire, add example of it

### ISSUE THREAD

**Issue by DeflateAwning** [wireviz/WireViz#439]
I want to add a tiny loopback wire as shown in the following diagram (pink jagged line).

The rest of the diagram is below. 

This would be great to add as an example if it's currently possible; otherwise, it'd be a great feature to add! 

![image](https://github.com/user-attachments/assets/0d07ef1d-55c3-4dcd-b646-0e3d963c65c1)

<details>

```yaml
connectors:
  CN1 (AC Input):
    type: JST B3P-VH on PCB, JST SVH-21T-P1.1 on wire, JST VHR housing
    subtype: female
    pinlabels: [Neutral, N/C, Line]
  CN2 (DC Output):
    type: JST B8P-VH on PCB, JST SVH-21T-P1.1 on wire, JST VHR housing
    subtype: female
    pinlabels: [+V, +V, +V, +V, -V, -V, -V, -V]
  CN3 (Power Good):
    type: JST B4B-XH on PCB, JST SXH-001T-P0.6 on wire, JST XHP housing
    subtype: female
    pinlabels: [PG, GND, Neg Sense, Pos Sense]
  CN901 (Standby):
    type: JST B-XH on PCB, JST SXH-001T on wire, JST XHP housing
    subtype: female
    pinlabels: [N_PS_ON, GND, 5VSB, GND]

  AC Input:
    subtype: female
    pinlabels: [Line, N/C, Neutral]

  Main Connector:
    subtype: female
    pinlabels: [V1, V1, V1, RTN, RTN, RTN, Neg Sense, Pos Sense, Remote PS ON]

cables:
  AC Wire:
    # gauge: 0.25 mm2
    # length: 0.2
    color_code: DIN
    wirecount: 2

  Main Wire:
    # gauge: 0.25 mm2
    # length: 0.2
    color_code: DIN
    wirecount: 9

  Pigtail Loopback:
    # gauge: 0.25 mm2
    # length: 0.2
    color_code: DIN
    wirecount: 1

connections:
  -
    - CN1 (AC Input): [3, 1]
    - AC Wire: [1, 2]
    - AC Input: [1, 3]

  -
    - CN2 (DC Output): [1-3, 5-7]
    - Main Wire: [1-6]
    - Main Connector: [1-6]

  -
    - CN3 (Power Good): [3, 4]
    - Main Wire: [7, 8]
    - Main Connector: [7, 8]

  -
    - CN901 (Standby): [1]
    - Main Wire: [9]
    - Main Connector: [9]
```
</details>

**Comment by tobiasfalk** [comment]
What you described here in pink would not be a loop back wire since it goes from one connector to the other.

A way to short and loop wires inside one connector is worked on, https://github.com/wireviz/WireViz/pull/412

To do what you want, I would create its own wire.

**Comment by kvid** [comment]
@tobiasfalk wrote:
> What you described here in pink would not be a loop back wire since it goes from one connector to the other.
> 
> A way to short and loop wires inside one connector is worked on, #412

What @tobiasfalk is trying to explain, is that this feature request cannot be solved with the existing optional `loops` attribute of a connector, because those loops are only supported between pins at the same connector, and PR #412 tries to improve the existing functionality, but is still limited to loops or shorts between pins at the same connector.

> 
> To do what you want, I would create its own wire/cable.

A quick and dirty work-around to obtain what @DeflateAwning asks for, is to append these connections:
```yaml
  -
    - CN2 (DC Output): [8]
    - Pigtail Loopback
  -
    - CN901 (Standby): [2]
    - Pigtail Loopback
```
However, the rendering is not very pretty. It looks almost like two wires are spliced:
![issue439](https://github.com/user-attachments/assets/ed7ec805-a841-4f2e-9284-698d98c42183)
This method also opens up for more than two connections for the same wire, which is normally not possible in real life without some kind of splicing or mid-wire connections. A future version of WireViz might therefore give a warning or error about this.

Another work-around requires more know-how about how WireViz generates the Graphviz input:
```yaml
# The connectors are unchanged
cables:
  # The other cables are unchanged
  Pigtail Loopback:
    colors: [PK, PK]
    show_wirecount: false
    show_wirenumbers: false
connections:
  # The other connections are unchanged
  -
    - CN2 (DC Output): [8]
    - Pigtail Loopback: [1]
  -
    - CN901 (Standby): [2]
    - Pigtail Loopback: [2]
tweak:
  append: |
    "Pigtail Loopback":w1:e -- "Pigtail Loopback":w2:e [label=" " color="#000000:#ff66cc:#000000"]
```
And it looks a bit better:
![issue439_tweak](https://github.com/user-attachments/assets/06ef6829-5e10-4208-a914-335712855e5c)
However, the BOM will show that "Pigtail Loopback" is a 2-wire cable unless specifying `category: bundle`, but if doing that and specifying a non-zero length, it will be doubled in the BOM because we use two wires looped together.
